### ISSUE TITLE
dialyzer errors after upgrade to 2.0 (from 1.13) 

### ISSUE THREAD

**Issue by dvic** [appsignal/appsignal-elixir-phoenix#5]
I was not able to trace the source of these expressions (probably in `Appsignal.Plug`?), but I get the following kind of dialyzer errors when upgrading to 2.0:

```
lib/my_web/views/email_view.ex:1:unmatched_return
The expression produces a value of type:

nil | %Appsignal.Span{:reference => _, _ => _}

but this value is unmatched.

________________________________________________________________________________
lib/my_web/views/email_view.ex:2:guard_fail
The guard test:

is_atom(
  _ ::
    binary()
    | maybe_improper_list(
        binary() | maybe_improper_list(any(), binary() | []) | char(),
        binary() | []
      )
)

can never succeed.

________________________________________________________________________________
```

**Comment by jeffkreeftmeijer** [comment]
Hey @dvic, thanks for letting us know about this. I’ve pushed a fix which we’re currently [reviewing](https://github.com/appsignal/appsignal-elixir-phoenix/pull/6). If you have time, could you try it out locally by switching your app to using that branch, to see if that resolves the issue for you?

``` elixir
  defp deps do
    [
      {:appsignal_phoenix, github: "appsignal/appsignal-elixir-phoenix", branch: "non-binary-templates"},
    ]
  end
```

**Comment by dvic** [comment]
Thanks!

The `guard_fail` errors are fixed, but the `unmatched_return` errors still persist:

```
lib/my_web/views/email_view.ex:1:unmatched_return
The expression produces a value of type:

nil | %Appsignal.Span{:reference => _, _ => _}

but this value is unmatched.
```

We have in our `mix.exs` the following dialyzer config line:

`dialyzer: [flags: ["-Wunmatched_returns", "-Werror_handling", "-Wunderspecs"]],`

**Comment by dvic** [comment]
@jeffkreeftmeijer great to see the PR being merged! Do you have an idea where to look for the `unmatched_return` error? (like I mentioned above, this dialyzer error is still present). Or are we maybe a bit to strict with our setup and show we just disable this flag ;)?

**Comment by jeffkreeftmeijer** [comment]
Hey @dvic,

Thanks for helping us test this! I’ve just released 2.0.1, which includes the fix for the first error. I’ll reopen this one to look at the other error, and I’ll keep you posted. :)

**Comment by jeffkreeftmeijer** [comment]
Hey @dvic,

I've been looking at these, and I think I fixed most warnings we see in standard Phoenix apps. We're reviewing the patches internally, but it'd be great if you could run them locally to see if they also fix your issues:

``` elixir
 {:appsignal_phoenix, github: "appsignal/appsignal-elixir-phoenix"},
 {:appsignal_plug, github: "appsignal/appsignal-elixir-plug", override: true},
 {:appsignal, github: "appsignal/appsignal-elixir", override: true}, 
```

Thanks!

**Comment by dvic** [comment]
I wanted to write "no" (because it didn't solve the issue) but then I saw you missed `branch: "unmatched-returns"` in the dependencies 🙂

I'm happy to report that those PRs solve all my dialyzer issues 👍!

As a reference for others, this is what I used:
```
      {:appsignal_phoenix, github: "appsignal/appsignal-elixir-phoenix", branch: "unmatched-returns"},
      {:appsignal_plug, github: "appsignal/appsignal-elixir-plug", branch: "unmatched-returns", override: true},
      {:appsignal, github: "appsignal/appsignal-elixir", branch: "unmatched-returns", override: true}
```

**Comment by jeffkreeftmeijer** [comment]
Hey @dvic,

Thanks, good catch! Great to hear these solved your issue. We’re working on some other patches, and we’ll release these as soon as those are merged. I’ll keep you posted!

**Comment by jeffkreeftmeijer** [comment]
Hey @dvic,

We’ve released new versions of all of the libraries yesterday, which include the patches to fix the dialyzer warnings we’ve been seeing. Could you switch back to the dependencies sourced from hex and run `mix deps.update appsignal appsignal_plug appsignal_phoenix`? Please let us know if you run into any more issues.

I’m closing this one, but feel free to reopen if the problem reappears.

**Comment by dvic** [comment]
@jeffkreeftmeijer works great, thanks!

**Comment by dvic** [comment]
@jeffkreeftmeijer One more question though: what about ignoring actions? As you might recall from our earlier conversations through support, we are using the following plug to ignore Kubernetes readiness/liveness probes:

```elixir
  def call(%Plug.Conn{} = conn, _opts) do
    if Enum.any?(conn.req_headers, &(&1 == {"user-agent", "k8s-probe"})) do
      Appsignal.Transaction.set_action("K8sProbeAction")
    end

    conn
  end
```

But `Transaction.set_action` is deprecated and does not do anything anymore, are you aware of this? Maybe it's better to remove that function and cause a compile error? When I read 'deprecated' I assumed that it was still working but this isn't the case :)

What is the recommended approach to do this in Appsignal v2? Implement a macro (like Appsignal.Plug) that starts a new span and sets a name there before continuing? Or is there another (better) way?

**Comment by jeffkreeftmeijer** [comment]
Hey @dvic,

That’s right. We removed the `Transaction` module, and chose to add deprecations there to make sure we don’t break compilation for our customer’s applications. You’re right that we could make it a bit clearer that the name-setting isn’t working, though. I’ll take a better look at that.

As for setting the span names, we’ve added a note to our [upgrade guide](https://docs.appsignal.com/elixir/installation/upgrading-from-1.x-to-2.x.html#custom-instrumentation) about that. Does that get you a step further?

**Comment by dvic** [comment]
@jeffkreeftmeijer totally missed that part, thanks, that will do!
